In [ ]:
# broadcasting in numpy: broadcast means to perform an operation on arrays of different shapes.
# broadcast is a numpy feature that allows numpy to work with arrays of different shapes. andd is used for elementwise operations.

# broadcast rules:
# 1. if the arrays have the same shape, elementwise operations can be performed.
# 2. if the arrays have different shapes, numpy will try to broadcast the smaller array to match the shape of the larger array.

# broadcasting types:
# 1. elementwise broadcasting: when the arrays have the same shape.
# 2. array broadcasting: when the arrays have different shapes.


# broadcast example:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 + arr2


In [2]:
# broadcasting

import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])

print(x + y)


[ 2  4  6  8 10]


In [ ]:
# array and scalar broadcast

# scalar broadcast
arr=np.array([1,2,3,4,5])
print(arr+5)
print(arr*5)

# array broadcast
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix+5)
print(matrix*5)

vector=np.array([1,0,1])
print(matrix+vector)

# element wise broadcast

[ 6  7  8  9 10]
[ 5 10 15 20 25]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [23]:
# aggregate functions: min, max, sum, std, var, 

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("min:", matrix.min())
print("max:", matrix.max())
print("sum:", matrix.sum())
print("std:", matrix.std())
print("var:", matrix.var())

print("sum of columns:",np.sum(matrix, axis=0))# sum of columns
print("sum of rows:",np.sum(matrix, axis=1))# sum of rows

print(matrix.max(axis=0))
print(matrix.max(axis=1))

# arg functions: arg means maximum or minimum index of the array
print(matrix.argmax()) #argmax returns the index of the maximum value of the array
print(matrix.argmin()) #argmin returns the index of the minimum value of the array

print(matrix.argmax(axis=0))
print(matrix.argmax(axis=1))


min: 1
max: 9
sum: 45
std: 2.581988897471611
var: 6.666666666666667
sum of columns: [12 15 18]
sum of rows: [ 6 15 24]
[7 8 9]
[3 6 9]
8
0
[2 2 2]
[2 2 2]


In [21]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

print(np.matmul(matrix,matrix))
#matmul: matrix multiplication

print("sum of matrix:",np.sum(matrix))
print("min of matrix:",np.min(matrix))
print("max of matrix:",np.max(matrix))
print("var of matrix:",np.var(matrix))
print("std of matrix:",np.std(matrix))
print("mean of matrix:",np.mean(matrix))

print("trace of matrix:",np.trace(matrix))
#trace: sum of diagonal elements

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
sum of matrix: 45
min of matrix: 1
max of matrix: 9
var of matrix: 6.666666666666667
std of matrix: 2.581988897471611
mean of matrix: 5.0
trace of matrix: 15


In [ ]:
# boolean indexing and filtering

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix > 5)

print(matrix[matrix > 5])
# print(matrix[matrix > 5]) here we are filtering the matrix and printing the values greater than 5

even=matrix[matrix%2==0]
print(even)

odd=matrix[matrix%2!=0] #it prints the odd values
print(odd)

odd= [matrix%2!=0] #it prints the boolean values
print(odd)

matrix[matrix>5]=0
print(matrix)

print("modified matrix: ",matrix)
print("max value of modified matrix: ",matrix.max())
print("min value of modified matrix: ",matrix.min())
print("sum value of modified matrix: ",matrix.sum())

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[2 4 6 8]
[1 3 5 7 9]
[array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])]
[[1 2 3]
 [4 5 0]
 [0 0 0]]
modified matrix:  [[1 2 3]
 [4 5 0]
 [0 0 0]]
max value of modified matrix:  5
min value of modified matrix:  0
sum value of modified matrix:  15


In [47]:
# random number generation

random_array=np.random.rand(3,3)
print(random_array)


[[0.64858888 0.75402952 0.37183397]
 [0.9145127  0.7704381  0.1477571 ]
 [0.34685574 0.08946878 0.9654679 ]]


In [48]:
random_array=np.random.randint(1,100,size=(5,5))
print(random_array)

random_integers=np.random.randint(1,100,size=(5,5))
print(random_integers)

[[86 72 74 97 20]
 [25 87 78 14 74]
 [83 57 47 56 68]
 [43 75 57 13 45]
 [60 31  7 19 94]]
[[81 47 60 94 80]
 [19 29 17 13 59]
 [96 60 39 59 40]
 [26 85 13 10 88]
 [19 47 93 98 40]]


In [59]:
# setting random seeds

np.random.seed(1) #seed is used to generate the same random numbers even if we run the code multiple times it will generate the same random numbers
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

[[6 9 6]
 [1 1 2]
 [8 7 3]]


exercise

In [65]:
# broadcast
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original matrix:", matrix)
print("broadcasted matrix:", matrix+1)

print("elementwise broadcast:", matrix+np.array([1,2,3]))

vector=np.array([1,2,3])
print("vector:", vector)
print("broadcasted vector:", vector+1)
print("elementwise broadcast:", vector+np.array([1,2,3]))


print("broadcasting with different shapes:")
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
vector=np.array([1,2,3])
print("matrix:", matrix)
print("vector:", vector)
print("broadcasted matrix:", matrix+vector)
print("elementwise broadcast:", matrix+np.array([1,2,3]))

result_mul=matrix*vector
print("result of multiplication:", result_mul)

original matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
broadcasted matrix: [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
elementwise broadcast: [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
vector: [1 2 3]
broadcasted vector: [2 3 4]
elementwise broadcast: [2 4 6]
broadcasting with different shapes:
matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
vector: [1 2 3]
broadcasted matrix: [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
elementwise broadcast: [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
result of multiplication: [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [ ]:
# generate and filter a random dataset

matrix=np.random.randint(1,230,(5,5))
print(matrix)

print("sum of matrix:",np.sum(matrix))
print("mean of matrix:",np.mean(matrix))
print("max of matrix:",np.max(matrix))
print("min of matrix:",np.min(matrix))
print("standard deviation of matrix:",np.std(matrix))

# filter the matrix
filtered_matrix=matrix[matrix>10]
print(filtered_matrix)

filtered_matrix=matrix[matrix<10]
print(filtered_matrix)

filtered_matrix=matrix[matrix%2==0]
print(filtered_matrix)

filtered_matrix=matrix[matrix%2!=0]
print(filtered_matrix)

matrix[matrix>25]=0
print(matrix)



[[ 22 175 125 132 185]
 [ 89 209 175  55 208]
 [ 72  15 206 144 154]
 [ 54 213 187 214 115]
 [158  45  38 151 220]]
sum of matrix: 3361
mean of matrix: 134.44
max of matrix: 220
min of matrix: 15
standard deviation of matrix: 66.10662901706606
[ 22 175 125 132 185  89 209 175  55 208  72  15 206 144 154  54 213 187
 214 115 158  45  38 151 220]
[]
[ 22 132 208  72 206 144 154  54 214 158  38 220]
[175 125 185  89 209 175  55  15 213 187 115  45 151]
[[22  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0 15  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [ ]:
# create a 3d random array and compute statistics along the specified axis

random_array=np.random.randint(1,50,(3,3,3))
print("random array",random_array)
print("mean of array along axis 0",random_array.mean(axis=0))
print("mean of array along axis 1",random_array.mean(axis=1))
print("mean of array along axis 2",random_array.mean(axis=2))

print("sum of array along axis 0",random_array.sum(axis=0))
print("sum of array along axis 1",random_array.sum(axis=1))
print("sum of array along axis 2",random_array.sum(axis=2))

print("max of array along axis 0",random_array.max(axis=0))
print("max of array along axis 1",random_array.max(axis=1))
print("max of array along axis 2",random_array.max(axis=2))

print("min of array along axis 0",random_array.min(axis=0))
print("min of array along axis 1",random_array.min(axis=1))
print("min of array along axis 2",random_array.min(axis=2))

print("standard deviation of array along axis 0",random_array.std(axis=0))
print("standard deviation of array along axis 1",random_array.std(axis=1))
print("standard deviation of array along axis 2",random_array.std(axis=2))

print("sum of array along axis 0",random_array.sum(axis=0,keepdims=True)) #keepdims=True will keep the dimensions of the array
print("sum of array along axis 1",random_array.sum(axis=1,keepdims=True))
print("sum of array along axis 2",random_array.sum(axis=2,keepdims=True))

random array [[[46 41 43]
  [12 23  7]
  [33 15 37]]

 [[24 12 36]
  [33 47 28]
  [39  1 23]]

 [[34  7 37]
  [19 28 29]
  [38 39 31]]]
mean of array along axis 0 [[34.66666667 20.         38.66666667]
 [21.33333333 32.66666667 21.33333333]
 [36.66666667 18.33333333 30.33333333]]
mean of array along axis 1 [[30.33333333 26.33333333 29.        ]
 [32.         20.         29.        ]
 [30.33333333 24.66666667 32.33333333]]
mean of array along axis 2 [[43.33333333 14.         28.33333333]
 [24.         36.         21.        ]
 [26.         25.33333333 36.        ]]
sum of array along axis 0 [[104  60 116]
 [ 64  98  64]
 [110  55  91]]
sum of array along axis 1 [[91 79 87]
 [96 60 87]
 [91 74 97]]
sum of array along axis 2 [[130  42  85]
 [ 72 108  63]
 [ 78  76 108]]
max of array along axis 0 [[46 41 43]
 [33 47 29]
 [39 39 37]]
max of array along axis 1 [[46 41 43]
 [39 47 36]
 [38 39 37]]
max of array along axis 2 [[46 23 37]
 [36 47 39]
 [37 29 39]]
min of array along axis 0 [[24  7

In [87]:
# write a program to genarate a dataset of random floats and normalize the value b/w 0 and 1
a=np.random.randn(10)
print(a)
print("normalized data:", (a-a.min())/(a.max()-a.min()))

# normalise between -1 and 1
print("normalized data:", (a-a.min())/(a.max()-a.min()))



[ 1.63015193 -0.46505859 -1.30430751 -0.59835746 -0.82895532 -0.45722768
  0.82276104 -1.92208722 -2.04354913  1.94295389]
normalized data: [0.92153475 0.39595869 0.18543611 0.36252115 0.30467651 0.39792305
 0.71900364 0.03046828 0.         1.        ]
normalized data: [0.92153475 0.39595869 0.18543611 0.36252115 0.30467651 0.39792305
 0.71900364 0.03046828 0.         1.        ]


In [ ]:
# write a program to genarate a dataset of random floats and save it to a file

a=np.random.rand(1000)
np.save("random_floats.npy", a)

# load the dataset from the file
b=np.load("random_floats.npy")
print(b)

# write a program to generate a dataset of random integers and save it to a file
a=np.random.randint(0,100,1000)
np.save("random_ints.npy", a)

# load the dataset from the file
b=np.load("random_ints.npy")
print(b)


[0.59027645 0.61925909 0.63905322 0.32637139 0.03302902 0.78817638
 0.71018785 0.07903169 0.14858184 0.68634024 0.53503738 0.19121444
 0.05595335 0.6114123  0.05361163 0.21357531 0.50266267 0.09403111
 0.40890611 0.0201158  0.11946375 0.94006251 0.55886109 0.68646138
 0.3777702  0.76312141 0.89638903 0.91019216 0.49648615 0.76261023
 0.70896203 0.95129685 0.24155449 0.56133971 0.04377327 0.92317796
 0.94525658 0.50090634 0.58611745 0.77194185 0.24933118 0.37899048
 0.2886056  0.53880397 0.94895682 0.3854007  0.04500977 0.68251863
 0.49503066 0.296512   0.41588861 0.8625103  0.82101771 0.17084634
 0.68513328 0.99766336 0.7843593  0.72504636 0.31001998 0.15947079
 0.86432215 0.61034622 0.3900904  0.75559073 0.71862789 0.64733313
 0.20726336 0.88552782 0.71900596 0.30263056 0.0635985  0.91279642
 0.79385006 0.49858364 0.41392519 0.61556247 0.39851518 0.03891804
 0.30196833 0.24627856 0.97230259 0.76749805 0.40369661 0.73662721
 0.30265502 0.52729583 0.20714324 0.25426028 0.43402307 0.0824

In [92]:
# implement conditional replacement to create a binary mask for values above a threshold
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(mask)
arr[mask] = 0
print(arr)


[False False False  True  True]
[1 2 3 0 0]
