In [1]:
# numpy: is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
# numpy in ai is used for data analysis and data science.
# numpy is a package for scientific computing with Python.
# numpy is used in machine learning, data analysis,data visualization,data mining, and data wrangling.
# numpy is used in deep learning, computer vision, natural language processing, and robotics.

# numpy integration with other libraries:
# numpy is used with pandas, matplotlib, and seaborn.
# numpy is used with scikit-learn, tensorflow, and pytorch.


# creating numpy array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# creating numpy array with different data types:
import numpy as np
arr = np.array([1, 2, 3, 4, 5], dtype = float)
print(arr)
print(type(arr))

# creating numpy array with different dimensions:
import numpy as np
arr = np.array([1, 2, 3, 4, 5], ndmin = 5)
print(arr)
print("number of dimensions :", arr.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In [5]:
zeroes=np.zeros((3,3))
print(zeroes)

ones=np.ones((3,3))
print(ones)

diag=np.diag([1,2,3])
print(diag)

hor=np.histogram([1,2,3])
print(hor)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
(array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1]), array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. ]))


In [13]:
range_array=np.arange(1,10,2)
print(range_array)

range_array=np.arange(1,10,3)
print(range_array)



[1 3 5 7 9]
[1 4 7]


In [ ]:
# linspace : it is used to create an array with a specified number of elements between two values. with evenly spaced values.
linspace_array=np.linspace(0,1,5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# manipulating arrays
arr=np.array([1,2,3,4,5,6])
reshape=arr.reshape(2,3)
print(reshape)

arr=np.array([1,2,3,4,5,6])
reshape=arr.reshape(3,2)
print(reshape)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
# adding dimensions

arr=np.array([1,2,3,4,5,6])
expanded=arr[:, np.newaxis]
print(expanded)



[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [24]:
# basic operations on array

a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

print("addition of a and b",a+b)
print("subtraction of a and b",a-b)
print("multiplication of a and b",a*b)
print("division of a and b",a/b)
print("modulus of a and b",a%b)

addition of a and b [ 7  9 11 13 15]
subtraction of a and b [-5 -5 -5 -5 -5]
multiplication of a and b [ 6 14 24 36 50]
division of a and b [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
modulus of a and b [1 2 3 4 5]


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 7  9 11 13 15]


In [28]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print("square root of a:",np.sqrt(a))
print("sum of a:",np.sum(a))
print("max of a:",np.max(a))
print("min of a:",np.min(a))
print("mean of a:",np.mean(a))
print("median of a:",np.median(a))
print("variance of a:",np.var(a))
print("standard deviation of a:",np.std(a))

square root of a: [1.         1.41421356 1.73205081 2.         2.23606798]
sum of a: 15
max of a: 5
min of a: 1
mean of a: 3.0
median of a: 3.0
variance of a: 2.0
standard deviation of a: 1.4142135623730951


In [ ]:
# array indexing, slicing and reshaping

In [ ]:
# indexing
a=np.array([1,2,3,4,5,6])
print("indexing :",a[0])
print("indexing :",a[-1])

# array slicing
print("array slicing :",a[1:4])
print(a[:3])
print(a[::-1])

# array iteration
for i in a:
    print("array iteration :",i)

# reshape
print("reshape :",a.reshape(2,3))

# array math
print("array math :",a+1)
print("array math :",a-1)
print("array math :",a*2)
print("array math :",a/2)

# array comparison
print("array comparison :",a==1)
print("array comparison :",a>1)
print("array comparison :",a<1)

# array statistics
print("array statistics :",np.mean(a))
print("array statistics :",np.median(a))
print("array statistics :",np.std(a))

# array sorting
print("array sorting :",np.sort(a))

# array joining
b=np.array([6,7,8,9,10])
print("array joining :",np.concatenate((a,b)))

# array splitting
print("array splitting :",np.split(a,2))
print("array splitting :",np.split(a,3))

# array stacking
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print("array stacking :",np.stack((a,b)))


indexing : 1
indexing : 6
array slicing : [2 3 4]
[1 2 3]
[6 5 4 3 2 1]
array iteration : 1
array iteration : 2
array iteration : 3
array iteration : 4
array iteration : 5
array iteration : 6
reshape : [[1 2 3]
 [4 5 6]]
array math : [2 3 4 5 6 7]
array math : [0 1 2 3 4 5]
array math : [ 2  4  6  8 10 12]
array math : [0.5 1.  1.5 2.  2.5 3. ]
array comparison : [ True False False False False False]
array comparison : [False  True  True  True  True  True]
array comparison : [False False False False False False]
array statistics : 3.5
array statistics : 3.5
array statistics : 1.707825127659933
array sorting : [1 2 3 4 5 6]
array joining : [ 1  2  3  4  5  6  6  7  8  9 10]
array splitting : [array([1, 2, 3]), array([4, 5, 6])]
array splitting : [array([1, 2]), array([3, 4]), array([5, 6])]
array stacking : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [53]:
# genearte arrays for basic mathematical operations

a=np.array(int(input("enter the array elements: ").split(',')))
b=np.array(int(input("enter the array elements: ").split(',')))

print("addition of arrays: ",a+b)
print("subtraction of arrays: ",a-b)
print("multiplication of arrays: ",a*b)
print("division of arrays: ",a/b)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [ ]:
# genearte arrays for basic mathematical operations

a=np.arange(1,6)
b=np.arange(6,11)

print("add: ",a+b)
print("sub: ",a-b)
print("mul: ",a*b)
print("div: ",a/b)

add:  [ 7  9 11 13 15]
sub:  [-5 -5 -5 -5 -5]
mul:  [ 6 14 24 36 50]
div:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [63]:
# create a 3x3 ,atrix and performance operations on it

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

print(np.dot(a,b)) #difference b/w * and dot is that dot is matrix multiplication. * is element wise multiplication
print(np.vdot(a,b)) #vdot is vector dot product

print(np.trace(a)) #trace is sum of diagonal elements

print("orignal matrix : \n",a)

transpose=a.T
print("transpose : \n",transpose)



[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
285
15
orignal matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# create a 4x4 matrix and calculate the sum of its rows and columns

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
# axis means dimension in numpy
# axis=1 means row
# axis=0 means column
print("sum of rows:",np.sum(a,axis=1))# explain axis=1: it will calculate the sum of rows
print("sum of columns:",np.sum(a,axis=0)) # explain axis=0: it will calculate the sum of columns

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of rows: [10 26 42 58]
sum of columns: [28 32 36 40]


In [68]:
# write a program to normalize an array
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("original array:",a)
print("normalized array: \n",a/np.linalg.norm(a))
# normalize formula in arrays : a/|a|

original array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
normalized array: 
 [[0.05096472 0.10192944 0.15289416 0.20385888 0.2548236 ]
 [0.30578831 0.35675303 0.40771775 0.45868247 0.50964719]]


In [75]:
# genrate a random array and find the minimum and maximum value
import random
a=np.random.random(45)
print(a)
print(min(a))
print(max(a))

a=np.random.randint(1,100,10)
print(a)
print(min(a))
print(max(a))

a=np.array([1,2,3,4,5])
print(a)
print(min(a))
print(max(a))

[0.93948531 0.9476823  0.93323952 0.03779735 0.86263521 0.72416179
 0.7581095  0.86914312 0.44154794 0.41502096 0.6060616  0.92775073
 0.05410985 0.20611137 0.79780672 0.23246553 0.31907364 0.90748886
 0.86583445 0.3319202  0.56581756 0.21242879 0.53915644 0.75631312
 0.8856047  0.310425   0.17894135 0.07318917 0.20002984 0.76271591
 0.28607621 0.28269862 0.14028582 0.5942151  0.35036176 0.76633446
 0.58179731 0.83053305 0.72555219 0.89674056 0.34215705 0.96895398
 0.88223057 0.9934877  0.20017765]
0.03779734644289945
0.9934876959634004
[48 26 54 79 90 31 21 50 69 62]
21
90
[1 2 3 4 5]
1
5
