In [2]:
# # linear_algebra:
#     -Vectors
#         - Vector addition
#         - Scalar multiplication
#         - Dot product
#         - Cross product
#     - Examples:
#         - [2,3,4]


#     -Matrices
#     -Examples:
#     -[[1,2,3],[4,5,6],[7,8,9]]
#         - Matrix addition
#         - Matrix multiplication
#         - Inverse
#         - Transpose


#     -Linear transformations
#     -Examples:
#     -[[1,2,3],[4,5,6],[7,8,9]]
#         - Linear transformation


#     - Eigenvalues and eigenvectors
#     -Examples:
#     -[[1,2,3],[4,5,6],[7,8,9]]
#         - Eigenvalues and eigenvectors

In [3]:
# matrix properties:
# 1.matrix is a 2D array of numbers
# 2.matrix is a collection of rows and columns
# 3.matrix is a collection of vectors
# 4.matrix is a collection of scalars
# 5.matrix is a collection of functions
# 6.matrix is a collection of polynomials
# 7.matrix is a collection of matrices

In [4]:
# matrix operations
# 1.addition
# 2.subtraction
# 3.multiplication
# 4.division

In [5]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print("matrix a: \n",a)
print("matrix b: \n",b)

print("addition of matrix: \n",a+b)
print("subtraction of matrix: \n",a-b)
print("multiplication of matrix: \n",a*b)
print("division of matrix: \n",a/b)

matrix a: 
 [[1 2]
 [3 4]]
matrix b: 
 [[1 2]
 [3 4]]
addition of matrix: 
 [[2 4]
 [6 8]]
subtraction of matrix: 
 [[0 0]
 [0 0]]
multiplication of matrix: 
 [[ 1  4]
 [ 9 16]]
division of matrix: 
 [[1. 1.]
 [1. 1.]]


In [6]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])

# scalar multiplication
print("scalar multiplication : \n",a*2)

# elementwise multiplication
print("elementwise multiplication\n",a*b)

# matrix multiplication : no. of rows of first matrix should be equal to no. of columns of second matrix
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[1,2],[3,4],[5,6]])
c=np.dot(a,b)
print("matrix multiplication\n",c)

# transpose
print("transpose\n",a.T)

a=np.random.randint(1,10,(3,2))
b=np.random.randint(1,10,(2,3))
print(a)
print(b)
print(np.dot(a,b))

scalar multiplication : 
 [[2 4]
 [6 8]]
elementwise multiplication
 [[ 1  4]
 [ 9 16]]
matrix multiplication
 [[22 28]
 [40 52]]
transpose
 [[1 3]
 [2 4]
 [3 5]]
[[8 5]
 [1 9]
 [1 9]]
[[1 8 9]
 [2 4 2]]
[[18 84 82]
 [19 44 27]
 [19 44 27]]


In [7]:
# special matrix
# 1.identity matrix
# 2.zero matrix
# 3.diagonal matrix
# 4.upper triangular matrix
# 5.lower triangular matrix

In [8]:
# identity matrix: identity matrix is a square matrix in which all the elements below the main diagonal are zero
I=np.eye(3,3)
print("identity matrix",I)

# zero matrix: zero matrix is a matrix in which all the elements are zero
Z=np.zeros((3,3))
print("zero matrix \n",Z)

# diagonal matrix: diagonal elements are non-zero and other elements are zero
D=np.diag([1,2,3])
print("diagonal matrix \n",D)

# upper triangular matrix: upper triangular matrix is a matrix in which all the elements below the main diagonal are zero
U=np.triu(np.ones((3,3)))
print("upper triangular matrix \n",U)

# lower triangular matrix: lower triangular matrix is a matrix in which all the elements above the main diagonal are zero
L=np.tril(np.ones((3,3)))
print("lower triangular matrix \n",L)

identity matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
zero matrix 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
diagonal matrix 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
upper triangular matrix 
 [[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
lower triangular matrix 
 [[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [9]:
# excerise

In [10]:
# 1. create vectors and matrices using numpy
import numpy as np
v=np.array([1,2,3])
m=np.array([[1,2,3],[4,5,6]])
print("vector:",v)
print("matrix:",m)

# 2. perform vector and matrix operations
# vector operations
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print("vector addition:",v1+v2)
print("vector subtraction:",v1-v2)
print("vector dot product:",np.dot(v1,v2))
print("vector cross product:",np.cross(v1,v2))


vector: [1 2 3]
matrix: [[1 2 3]
 [4 5 6]]
vector addition: [5 7 9]
vector subtraction: [-3 -3 -3]
vector dot product: 32
vector cross product: [-3  6 -3]


In [18]:

# matrix operations
m1=np.array([[1,2,3],[4,5,6],[7,8,10]])
m2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix addition:",m1+m2)
print("matrix subtraction:",m1-m2)
print("matrix dot product:",np.dot(m1,m2))
print("matrix transpose:",m1.T)
print("detreminant: \n",np.linalg.det(m1))
print("matrix inverse: \n",np.linalg.inv(m1))


matrix addition: [[ 2  4  6]
 [ 8 10 12]
 [14 16 19]]
matrix subtraction: [[0 0 0]
 [0 0 0]
 [0 0 1]]
matrix dot product: [[ 30  36  42]
 [ 66  81  96]
 [109 134 159]]
matrix transpose: [[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]
detreminant: 
 -2.9999999999999996
matrix inverse: 
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [12]:
# 2.matrix-vector multiplication
V=np.array([1,0,-1])
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix-vector multiplication:",np.dot(m1,V))

matrix-vector multiplication: [-2 -2 -2]


In [13]:
# dot product working: first row of first matrix is multiplied with first column of second matrix

In [14]:
# explore special matrix

# identity matrix
I=np.eye(3)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A X I =\n",np.dot(a,I))

# zero matrix
z=np.zeros((3,3))
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A X Z =\n",np.dot(a,z))

# ones matrix
o=np.ones((3,3))
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A X O =\n",np.dot(a,o))

# diagonal matrix
d=np.diag([1,2,3])
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A X D =\n",np.dot(a,d))

# upper triangular matrix
u=np.triu(np.ones((3,3)))
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A X U =\n",np.dot(a,u))

# lower triangular matrix
l=np.tril(np.ones((3,3)))
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A X L =\n",np.dot(a,l))

A X I =
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A X Z =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
A X O =
 [[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]
A X D =
 [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
A X U =
 [[ 1.  3.  6.]
 [ 4.  9. 15.]
 [ 7. 15. 24.]]
A X L =
 [[ 6.  5.  3.]
 [15. 11.  6.]
 [24. 17.  9.]]


In [15]:
# compute the determinant of a matrix
a=np.array([[1,2,3],[4,5,6],[7,8,10]])
print("determinant of a:",np.linalg.det(a))

# compute the inverse of a matrix
a=np.array([[1,2,3],[4,5,6],[7,8,10]])
print("inverse of a: \n",np.linalg.inv(a))

# eigenvalues working: it is the value of lambda for which the matrix (A - lambda I) is singular
# where I is the identity matrix
# A is the matrix
# lambda is the eigenvalue

# eigenvectors working: it is the non-zero vector v such that Av = lambda v
# lambda is the eigenvalue

#eigenvalue finding for a matrix: eigenvalues are the roots of the characteristic equation of the matrix


# compute the eigenvalues and eigenvectors of a matrix
a=np.array([[1,2,3],[4,5,6],[7,8,10]])
eigenvalues,eigenvectors=np.linalg.eig(a)
print("eigenvalues of a: \n",eigenvalues)
print("eigenvectors of a: \n",eigenvectors)


determinant of a: -2.9999999999999996
inverse of a: 
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
eigenvalues of a: 
 [16.70749332 -0.90574018  0.19824686]
eigenvectors of a: 
 [[-0.22351336 -0.86584578  0.27829649]
 [-0.50394563  0.0856512  -0.8318468 ]
 [-0.83431444  0.4929249   0.48018951]]


In [16]:
# verify properties of matrix multiplication
# 1. commutative property: A * B = B * A
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix multiplication:",np.dot(a,b))
print("matrix multiplication:",np.dot(b,a))

# verify properties of matrix addition
# 2. associative property: (A + B) + C = A + (B + C)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix addition:\n",(np.add(a,b)+c))
print("matrix addition:\n",np.add(a,(np.add(b,c))))

# verify properties of matrix subtraction
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix subtraction:",np.subtract(a,b))
print("matrix subtraction:",np.subtract(b,a))

# verify properties of matrix multiplication
# 3. distributive property: A * (B + C) = A * B + A * C
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix multiplication:",np.dot(a,(np.add(b,c))))
print("matrix multiplication:",np.add(np.dot(a,b),np.dot(a,c)))

# verify properties of matrix multiplication
# 4. distributive property: (A + B) * C = A * C + B * C
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix multiplication:",np.dot((np.add(a,b)),c))
print("matrix multiplication:",np.add(np.dot(a,c),np.dot(b,c)))

# verify properties of matrix multiplication
# 5. associative property: (A * B) * C = A * (B * C)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix multiplication:",np.dot((np.dot(a,b)),c))
print("matrix multiplication:",np.dot(a,(np.dot(b,c))))
p

matrix multiplication: [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
matrix multiplication: [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
matrix addition:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
matrix addition:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
matrix subtraction: [[0 0 0]
 [0 0 0]
 [0 0 0]]
matrix subtraction: [[0 0 0]
 [0 0 0]
 [0 0 0]]
matrix multiplication: [[ 60  72  84]
 [132 162 192]
 [204 252 300]]
matrix multiplication: [[ 60  72  84]
 [132 162 192]
 [204 252 300]]
matrix multiplication: [[ 60  72  84]
 [132 162 192]
 [204 252 300]]
matrix multiplication: [[ 60  72  84]
 [132 162 192]
 [204 252 300]]
matrix multiplication: [[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]
matrix multiplication: [[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]


NameError: name 'p' is not defined

In [ ]:
# create a block diagonal matrix using numpy
a=np.diag([1,2,3])
b=np.diag([4,5,6])
c=np.block([[a, np.zeros((3,3))], [np.zeros((3,3)), b]])
print(c)

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]
