In [57]:
# deterimants: scalar value that can tell us some information about the matrix properties
# -such as whether it is invertible

# determinants are only defined for square matrices
# det(A) = 0 if A is not invertible, the matrix is singular
# det(A) != 0 if A is invertible, the matrix is non-singular

# geometrix interpretation
# -for 2x2 matrix, the determinant represents the scale factor of the area spanned by the column vectors of A
#  det(A) = area of the parallelogram spanned by the column vectors of A
# -for 3x3 matrix, det(A) = volume of the parallelepiped spanned by the column vectors of A

# formula for 2x2 matrix
# det(A) = ad - bc
# det([[a, b], [c, d]]) = ad - bc

In [58]:
import numpy as np

a=np.array([[1,2],[3,4]])
print("matrix a\n",a)
det=np.linalg.det(a)
print("determinant of a\n",det)
b=np.linalg.inv(a)
print("inverse of a\n",b)

matrix a
 [[1 2]
 [3 4]]
determinant of a
 -2.0000000000000004
inverse of a
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [59]:
# inverse of a matrix:
# - denoted as A^-1
# product of a matrix and its inverse is the identity matrix: A X A^-1 = I
# matrix is invertible only if det(A)!=0


In [60]:
# formula for a 2x2, 2x2 matrix

# A^-1 = (1/det(A))*[[d,-b],[-c,a]]

In [61]:
A=np.array([[2,3],[1,4]])
deteminant=np.linalg.det(A)
inverse=np.linalg.inv(A)

print("determinant: \n",deteminant)
print("inverse: \n",inverse)

determinant: 
 5.000000000000001
inverse: 
 [[ 0.8 -0.6]
 [-0.2  0.4]]


In [62]:
# eigenvalues and eigenvectors
# eigenvalues: 
# if A. v= lamda. v, then
#    -v is eigenvector and lamda is eigen values

# Geometric interpretation
    # -eigenvector points in the direction where the matrix transformation stretches or compresses Vector
    # -eigenvalue indicates the facotr of stretching or compression

# properties
    # -matrix of size nXn has n, n eigenvalues and eigenvector
    # -eigenvalues can be real or complex
    #  for a symmetric matrix, eigenvalues are always real

# computing eigenvalues and eigenvector using numpy


In [63]:
a=np.array([[1,2],[4,5]])
eigenvalues,eigenvectors = np.linalg.eig(a)
print("eigenvalues: \n",eigenvalues)
print("eigenvectors: \n",eigenvectors)

eigenvalues: 
 [-0.46410162  6.46410162]
eigenvectors: 
 [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [64]:
A=np.array([[4,2],[3,1]])
eigenvalues,eigenvectors = np.linalg.eig(A)
print("eigenvalues: \n",eigenvalues)
print("eigenvectors: \n",eigenvectors)

eigenvalues: 
 [ 5.37228132 -0.37228132]
eigenvectors: 
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]


In [65]:
# Matrix Decomposition
# Matrix Decomposition: process of breaking a matrix into simpler components to analyse or solve problems

# Singular Value Decomposition(SVD)
    # SVD decomposes a matrix into three components: U, S, and V
    # A=U*S*V^T
    # U: Orthogonal matrix(left singular vectors)
    # S: Diagonal matrix(non-negative singular values)
    # V: Orthogonal matrix(right singular vectors)

# applications of SVD
    # 1. Data compression
    # 2. Noise reduction
    # 3. Image processing
    # 4. Signal processing
    # 5. Machine learning

In [66]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,Vt=np.linalg.svd(A)
print("U:\n",U)
print("Singular values:\n",S)
print("V Transpose:\n",Vt)

U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values:
 [1.68481034e+01 1.06836951e+00 4.41842475e-16]
V Transpose:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [67]:
# excerise

In [68]:
# calculate the determinant and inverse of a matrix

A=np.array([[1,2,3],[3,4,4],[5,6,7]])
D=np.linalg.det(A)
I=np.linalg.inv(A)
print("The determinant of A is",D)
print("The inverse of A is",I)

The determinant of A is -3.999999999999999
The inverse of A is [[-1.   -1.    1.  ]
 [ 0.25  2.   -1.25]
 [ 0.5  -1.    0.5 ]]


In [69]:
# compute the eigenvalues and eigenvectors of a matrix

A=np.array([[4,2],[1,3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [70]:
# perform the SVD
M=np.array([[1,2],[4,5]])
U,S,Vt=np.linalg.svd(M)
print(U)
print(S)
print(Vt)

print()

# reconstruction
sigma=np.zeros((2,2))
np.fill_diagonal(sigma,S)
reconstructed_M=U @ sigma @ Vt
print(reconstructed_M)


# reconstruction
reconstructed_M=U @ np.diag(S) @ Vt
print(reconstructed_M)

# compute the pseudoinverse
M_pinv=np.dot(Vt.T, np.dot(np.diag(1/S), U.T))
print(M_pinv)

[[-0.32453643 -0.9458732 ]
 [-0.9458732   0.32453643]]
[6.76782894 0.44327362]
[[-0.60699365 -0.79470668]
 [ 0.79470668 -0.60699365]]

[[1. 2.]
 [4. 5.]]
[[1. 2.]
 [4. 5.]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [75]:
# USE SVD to reduce the dimensionality of a dataset
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,s,Vh=np.linalg.svd(A)
print(U)
print(s)
print(Vh)

# Reconstruct the original matrix
A_reduced=np.dot(np.dot(U, np.diag(s)), Vh)
print(A_reduced)


[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [72]:
# verify the property of eigenvalues: det(A-λI) = 0. here λ is the eigenvalue and I is the identity matrix
import numpy as np
A=np.array([[4,2],[1,3]])   
Property=np.linalg.det(A-np.array([[1,0],[0,1]]))
print(Property)


4.000000000000001


In [73]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenvalues,eigenvectors=np.linalg.eig(A)
property=np.linalg.det(A-eigenvalues*np.identity(3))
print(property)

-127.05159572826352
